#!/bin/bash

mem=$(free -h | awk 'NR==2 {print $3}')
disk=$(df -h | grep ' /$' | awk '{print $4}')
ssid=$(iwgetid -r)
vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk 'NR==1 {print $5}')
mute_status=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
[ "$mute_status" == "yes" ] && mute=" (mute)" || mute=""
datetime=$(date +"%d - %H:%M")
bat=$(cat /sys/class/power_supply/BAT0/capacity)
bat_status=$(cat /sys/class/power_supply/BAT0/status)
case "$bat_status" in
	Charging) icon="+" ;;
	Discharging) icon="-" ;;
	*) icon="o" ;;
esac

echo "<span color='#7dcfff'><u>Vol: $vol$mute</u></span>  \
<span color='#bb9af7'><u>Mem: $mem</u></span>  \
<span color='#e0af68'><u>Disk: $disk</u></span>  \
<span color='#9ece6a'><u>Wifi: $ssid</u></span>  \
<span color='#7aa2f7'><u>Bat: $bat$icon</u></span>  \
<span color='#a9b1d6'><u>$datetime</u></span>"
