#!/bin/bash

# Modules
User=$(whoami)
Hostname=$(cat /etc/hostname)
OS=$(grep "PRETTY_NAME" /etc/os-release | cut -d '"' -f2)
Kernel=$(uname -r)
Pacman=$(pacman -Q | wc -l)
Shell=$($SHELL --version | grep $(basename $SHELL) | awk '{print $2 $4}' | tr ',' ' ' | cut -d '(' -f1)
Uptime=$(uptime -p | awk '{gsub(/up /, ""); print}')
Wm=$(ps -e | grep -m 1 dwm | awk '{print $4}')
Init=$(ps -p 1 -o comm=)

# Ascii art
cat <<EOF

   [1;34m       /\\[0m	     [1;34m$User[0m@[1;34m$Hostname[0m
   [1;34m      /  \\[0m	     [1;34mdistro[0m->  $OS
   [1;34m     /\`'.,\\[0m	     [1;34mkernel[0m->  $Kernel
   [1;34m    /     ',[0m	     [1;34muptime[0m->  $Uptime
   [1;34m   /      ,\`\\[0m     [1;34mpkgs[0m->    $Pacman
   [1;34m  /   ,.'\`.  \\[0m    [1;34minit[0m->    $Init
   [1;34m /.,'\`     \`'.\\[0m   [1;34mwm[0m->      $Wm
      
    
EOF
