#!/bin/bash

# Modules

User=$(whoami)
Hostname=$(cat /etc/hostname)
OS=$(awk -F= '/^PRETTY_NAME/ {gsub(/"/, "", $2); print $2}' /etc/os-release)
Kernel=$(uname -r)
Pacman=$(pacman -Q | wc -l)
Shell_name=$(echo $SHELL | sed 's/\/usr\/bin\///')
Shell=$($SHELL --version | grep $Shell_name | awk '{print $2}' | tr -d ',')
Uptime=$(uptime -p | awk '{gsub(/up /, ""); print}')
Wm=$(ps -e | grep -m 1 dwm | awk '{print $4}')
Init=$(ps -p 1 -o comm=)


# Void ascii art
cat <<EOF

   [1;34m       /\\[0m	     [1;34m$User[0m@[1;34m$Hostname[0m
   [1;34m      /  \\[0m	     [1;34mdistro[0m->  $OS
   [1;34m     /\`'.,\\[0m	     [1;34mkernel[0m->  $Kernel
   [1;34m    /     ',[0m	     [1;34muptime[0m->  $Uptime
   [1;34m   /      ,\`\\[0m     [1;34mpkgs[0m->    $Pacman
   [1;34m  /   ,.'\`.  \\[0m    [1;34minit[0m->    $Init
   [1;34m /.,'\`     \`'.\\[0m   [1;34mwm[0m->      $Wm
      
    
EOF
