#!/bin/bash

# Modules

User=$(whoami)
Hostname=$(cat /etc/hostname)
OS=$(awk -F= '/^PRETTY_NAME/ {gsub(/"/, "", $2); print $2}' /etc/os-release)
Kernel=$(uname -r)
Pacman=$(pacman -Q | wc -l)
Shell_name=$(echo $SHELL | sed 's/\/usr\/bin\///')
Shell=$($SHELL --version | grep $Shell_name | awk '{print $2}' | tr -d ',')
Uptime=$(uptime -p | awk '{gsub(/up /, ""); print}')
Wm=$(ps -e | grep -m 1 dwm | awk '{print $4}')


# Void ascii art
cat <<EOF

   [1;32m       /\\[0m	     [1;32m$User[0m@[1;32m$Hostname[0m
   [1;32m      /  \\[0m	     [1;32mdistro[0m->  $OS
   [1;32m     /\`'.,\\[0m	     [1;32mkernel[0m->  $Kernel
   [1;32m    /     ',[0m	     [1;32muptime[0m->  $Uptime
   [1;32m   /      ,\`\\[0m     [1;32mpkgs[0m->    $Pacman
   [1;32m  /   ,.'\`.  \\[0m    [1;32mshell[0m->   $Shell
   [1;32m /.,'\`     \`'.\\[0m   [1;32mwm[0m->      $Wm
      
    
EOF
