vim.o.winborder      = "single"
vim.o.signcolumn     = "yes"
vim.o.colorcolumn    = "80"
vim.o.tabstop        = 4
vim.o.shiftwidth     = 4
vim.o.wrap           = false
vim.o.swapfile       = false
vim.o.number         = true
vim.o.cursorline     = true
vim.o.relativenumber = true
vim.o.ignorecase     = true
vim.o.smartindent    = true
vim.o.termguicolors  = true
vim.o.list = true
vim.o.listchars = 'tab:» ,lead:·,trail:·'
