#!/bin/bash

SEARXNG_DIR="$HOME/searxng"
CONTAINER_NAME="searxng"
IMAGE_NAME="docker.io/searxng/searxng:latest"

check_error() {
	if [ $? -ne 0 ]; then
		echo "Error executing command: $1"
		exit 1
	fi
}

if docker ps -q -f name="$CONTAINER_NAME"; then
	echo "Stopping existing container $CONTAINER_NAME..."
	docker stop "$CONTAINER_NAME"
	check_error "docker stop $CONTAINER_NAME"
fi

if docker ps -a -q -f name="$CONTAINER_NAME"; then
	echo "Removing existing container $CONTAINER_NAME..."
	docker rm "$CONTAINER_NAME"
	check_error "docker rm $CONTAINER_NAME"
fi

# Run the container
docker run --name $CONTAINER_NAME -d \
    -p 8888:8080 \
    -v "$SEARXNG_DIR/config/:/etc/searxng/" \
    -v "$SEARXNG_DIR/data/:/var/cache/searxng/" \
    $IMAGE_NAME
    
check_error "docker run $IMAGE_NAME"
