#!/bin/bash

docker stop searxng
docker rm searxng
cd "$HOME/searxng/"

# Run the container
docker run --name searxng -d \
    -p 8888:8080 \
    -v "./config/:/etc/searxng/" \
    -v "./data/:/var/cache/searxng/" \
    docker.io/searxng/searxng:latest
