#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           10
bspc config top_padding          1
bspc config bottom_padding       1
bspc config left_padding         1
bspc config right_padding        1

bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config removal_adjustment true
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config normal_border_color "#000000"
bspc config focused_border_color "#ffffff"
bspc config focus_follows_pointer true


sxhkd &
dunst &
nitrogen --restore &
setxkbmap -layout br &
setxkbmap -option ctrl:nocaps &
xsetroot -cursor_name left_ptr &

