#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          15
bspc config top_padding          5
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#4c4c4c"
bspc config focused_border_color "#0A84FF"
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Xfce4-appfinder state=floating

/home/goku/autostart.sh
