set -a terminal-features "tmux-256color:RGB"
set -g mouse on
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "bold"
set -g status-left "#S"
set -g status-right "#[fg=#80a0ff] #(whoami)@#(hostname -s) #[fg=#d183e8] %a %m/%d %H:%M"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind p new-window "$HOME/.config/tmux/tmux-session-dispatcher.sh"
bind f new-window -n "lf" -S lf
bind r source-file "$HOME/.tmux.conf"
