set -a terminal-features "tmux-256color:RGB"
set -g mouse on
set -g renumber-windows on
set -g mode-keys vi
set -g status-position top
set -g status-style "bg=default,fg=colour248"
set -g status-right "#[fg=colour81] #(whoami)@#(hostname -s) #[fg=colour12] %a %m/%d %H:%M"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind p new-window "$HOME/.config/tmux/tmux-session-dispatcher.sh"
bind r source-file "$HOME/.tmux.conf"
